In [3]:
import numpy as np

In [61]:
numlist = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(numlist)
#print(arr * 4)
#print(np.mean(arr))
#print(np.median(arr))
#print(np.std(arr))
min = np.argmin(arr)
max = np.argmax(arr)
#print(arr[min])
#print(arr[max])
#print(np.min(arr))
#print(np.max(arr))
#print(arr[arr > 20])
        
matrix1 = [[5, 12, 17, 9], [8, 21, 14, 3], [6, 13, 19, 11]]
matrix = np.matrix(matrix1)
#print(matrix.shape)
#print(matrix[:, 2])
#print(matrix[1])
#print(matrix * 2)
#print(np.mean(matrix[0]), np.mean(matrix[1]), np.mean(matrix[2]))
#print(np.mean(matrix))
#print(np.max(matrix, axis = 1))
#print(np.min(matrix, axis = 0))
#print(matrix.flatten())
## new shape is an array, flattened it out into one long list
#print(np.argmin(matrix.flatten()))
#print(np.argmax(matrix.flatten()))
#print(matrix.flatten()[matrix.flatten() > 15])
#print(np.sort(matrix, axis = 1).flatten())
arr = ([2,3,5],[14,6,8],[11,13,17],[7,10,13])
def findprime(matrix):
    rows = []
    for row in matrix:
        for x in row:
            n = 2
            append = False
            while n <= x/2:
                if x % n == 0:
                    append = True
                n += 1
        if append == False:
            rows.append(row)
    return rows
#print(findprime(arr))

grid = (np.zeros((8,8)))
def checkerboard(input):
    tempgrid = input
    y = 0
    while y < len(grid):
        if y % 2 == 0:
            x = 0
            while x < len(grid):
                grid[y][x] = 1
                x += 2
        else: 
            x = 1
            while x < len(grid):
                grid[y][x] = 1
                x += 2
        y +=1
    return tempgrid
#print(checkerboard(grid))
def reverse_checkerboard(input):
    tempgrid2 = input
    y = 0
    while y < len(grid):
        if y % 2 == 0:
            x = 1
            while x < len(grid):
                grid[y][x] = 1
                x += 2
        else: 
            x = 0
            while x < len(grid):
                grid[y][x] = 1
                x += 2
        y +=1
    return tempgrid2
#print(reverse_checkerboard(grid))

universe = np.array(["galaxy", "clusters"])
def expansion(number, array):
    newarray = []
    for x in array:
        mylist = list(str(x))
        list_init_len = len(mylist)
        letter = 0
        while letter < (list_init_len * (number+1) ):
            n = 0
            while n < number:
                mylist.insert(letter + 1, " ")
                n += 1
            letter = letter + number + 1
        newarray.append(str(mylist))
    return newarray
#print(expansion(2, universe))

stars = np.random.randint(500, 2000, (5,5))
print(stars)
def secondDimmest(starlist):
    templist = starlist
    newarray = np.sort(templist)
    seconddimmestarray = []
    x = 0
    while x < len(newarray):
        seconddimmestarray.append(newarray[x][len(newarray) - 2])
        x += 1
    finalarray = np.array(seconddimmestarray)
    return finalarray
print(secondDimmest(stars))

[[1769 1688 1491  853 1234]
 [ 998 1427 1051 1836 1378]
 [1374 1756  726 1758  708]
 [1289  886  710 1969 1077]
 [1747  547 1291 1615 1629]]
[1688 1427 1756 1289 1629]
